services:
  ui:
    container_name: gpt-free-share-typescript-vue-nuxt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - network
networks:
  network:
    driver: bridge
